cloudforet-io/python-core

pkg/pip_requirements.txt
src/spaceone/core/utils.py

* Changed the dot argument to an immutable value in the change_dict_with_dot_notation function to solve the problem that the value was passed when the scope changed. ( dots = None )
* A function test was performed with the data below.
```python
dot_notation_sample = {
"a.b.c": "d",
"q.w.e.r": "t",
"a.b.b": "a",
"q.q.e.r": "t",
"b.c": "g"
}
dot_notation_sample2 = {
"a.b.c": "d",
"a.w.e.r": "t",
"b.b.b": "a",
"b.q.e.r": "t",
"b.c": "g"
}
nested_dict_sample = {
'a': {'b': {'c': 'd', 'b': 'a'}},
'q': {'w': {'e': {'r': 't'}}, 'q': {'e': {'r': 't'}}},
'b': {'c': 'g'}
}
nested_dict_sample2 = {
'a': {'g': {'k': 'l'}},
'q': {'n': {'k': {'u': 'y'}}}
}
{'a': {'b': {'c': 'd', 'b': 'a'}}, 'q': {'w': {'e': {'r': 't'}}, 'q': {'e': {'r': 't'}}}, 'b': {'c': 'g'}}
{'a': {'b': {'c': 'd'}, 'w': {'e': {'r': …
```

feat: add changable functions of nested key or dot notation dict in util

---

src/spaceone/core/command.py
src/spaceone/core/config/__init__.py
src/spaceone/core/config/default_conf.py

- add `show-config` command for checking global configuration
```
spaceone show-config --help
Usage: command.py show-config [OPTIONS] PACKAGE
Show global configurations
Options:
-c, --config-file PATH         Config file path
-m, --module-path PATH    Module path
-o, --output [json|yaml]  Output format  [default: yaml]
--help                    Show this message and exit.
```

feat add sub command for checking global configuration

---

src/spaceone/core/model/mongo_model/__init__.py
src/spaceone/core/model/mongo_model/stat_operator.py

- fix bug in `push` operator
- support array type for `sum`, `average`, `max`, `min` operators in analyze query

Support Array Type in Analyze Query

---

src/spaceone/core/service/service.py

* delete self.resource of _resource in transaction decorator because of console-api-v2' proxy service error

Delete self.resource of _resource in transaction decorator

---

src/spaceone/core/transaction.py

* add thread_id in transaction

Add thread_id in transaction

---

src/spaceone/core/opentelemetry/tracer.py

`ConsoleSpanExporter` inherits from `SpanExporter`. `SpanExporter` is the most basic implementation and is suitable for the situation we are going to use now.
Because Opentelemetry code depends on transaction of `python-core`
This is because even if Opentelemetry is not set, the default skeleton must be set to run.

Change from ConsoleSpanExporter to SpanExporter If opentelemetry is not set

---

src/spaceone/core/model/mongo_model/__init__.py

- refactor logic for start and end options

refactor: refactor logic for start and end options

---

src/spaceone/core/command.py

If you are using python 3.8+, remove `pkg_resources`
Since our microservices are using Python 3.8+, no need for `pkg_resources` anymore.
If you use Python 3.8+, `pkg_reousrces` will be deprecated, so I changed minor code for future development.

Resolve DeprecationWarning issue

---

src/spaceone/core/auth/jwt/jwt_util.py
src/spaceone/core/handler/authentication_handler.py

- add `get_value_from_token` method in JWTUtil

feat: add get_value_from_token method in JWTUtil

---

src/spaceone/core/error.py
src/spaceone/core/handler/authentication_handler.py
src/spaceone/core/handler/mutation_handler.py

In Service Account Agent mode, `injected_params`, in other words, `service_account_id`, are added to apps created by the Service Account. To handle this in the handler, code has been added.

Add injected_params for service account agent mode

---

src/spaceone/core/model/mongo_model/__init__.py

- refactor group_by option in analyze method

Refactor group_by option in analyze method

---

src/spaceone/core/model/mongo_model/__init__.py

refactor: refactor reference filter

---

pkg/pip_requirements.txt
src/setup.py

- fix pydantic package version

build: fix pydantic package version

---

src/spaceone/core/pygrpc/client.py

- refactor code for grpc compatability

refactor: refactor code for grpc compatability

---

src/spaceone/core/handler/authentication_handler.py

- modify app check response add accessible 'projects' info
Due to changes in the app check response, the core handler has been modified. This feature is related to the PR mentioned in the Known Issues section.
- identity
- https://github.com/cloudforet-io/identity/pull/302
- api
- https://github.com/cloudforet-io/api/pull/394

Modify app check response add accessible 'projects' info

---

src/spaceone/core/pygrpc/client.py

- Rollback proto file descriptor modification at client.py
python-core has a dependency on protobuf `3.20.3` . This version does not have `GetMessageClass`at **message_factory.py,** so we temporarily rolled back to the previous code.
- protobuf code [link](https://github.com/protocolbuffers/protobuf/blob/701dd83594c5d979481bc36ac58efea670a929ba/python/google/protobuf/message_factory.py) for `3.20.3`
The last commit before version 3.20.3 in message_factory.py was on 2022-08-22.
- protobuf 3.20.3 pypi package relase version date [link](https://pypi.org/project/protobuf/3.20.3/)
Version `3.20.3` was released on 2022-09-30
- https://github.com/cloudforet-io/python-core/pull/150

Rollback modification of proto file descriptor at client.py

---

src/spaceone/core/model/mongo_model/__init__.py

- apply hint option to query of MongoDB model

Apply hint option to query of MongoDB model

---

src/spaceone/core/model/mongo_model/__init__.py

- change unwind option in analyze query

feat: change unwind option in analyze query

---

src/spaceone/core/service/utils.py

feat: create "check_query_filter" for checking that parameters have secure fields.

create "check_query_filter" for checking that parameters have secure fields.

---

src/spaceone/core/handler/authentication_handler.py
src/spaceone/core/handler/mutation_handler.py

- fix project bug of WORKSPACE_MEMBER

fix project bug of WORKSPACE_MEMBER

---

src/spaceone/core/service/utils.py

fix: fix service util bug

---

src/spaceone/core/connector/space_connector.py
src/spaceone/core/pygrpc/client.py

test: rollback loggers

---

src/spaceone/core/pygrpc/client.py

test: add debug code for grpcclient.

test: add debug code for grpcclient.

---

src/spaceone/core/pygrpc/client.py

rollback: rollback test codes.

rollback: rollback test codes.

---

src/spaceone/core/service/__init__.py

- Implement response size logging

Implement response size logging

---

src/spaceone/core/connector/space_connector.py
src/spaceone/core/error.py
src/spaceone/core/pygrpc/client.py

- add a timeout settings to grpc client

refactor: add a timeout settings to grpc client

---

src/spaceone/core/connector/space_connector.py
src/spaceone/core/error.py
src/spaceone/core/pygrpc/client.py
src/spaceone/core/service/__init__.py

- modify calculate response size logic for mongoengine queryset

Modify calculate response size logic for mongoengine queryset

---

Dockerfile
pkg/pip_requirements.txt

- upgraded python version `3.8` -> `3.10` 
- when create core image, replaced PyPI-based spaceone-core install with local source installation using setup.py, with version injection via PACKAGE_VERSION
- We’ll need to upgrade to python`3.11` soon.

Update Dockerfile to use Python 3.10 and improve build process

---

src/spaceone/core/handler/__init__.py

- Add thread-safe handler initialization using double-checked locking
When the server starts and both the first and second requests arrive simultaneously, the handler was being initialized twice.
To resolve this, a thread lock was introduced. Only the first and second requests are affected by the lock, and since subsequent requests bypass the initialization logic, there appears to be no performance issue.

Add thread-safe handler initialization using double-checked locking

---

src/spaceone/core/model/mongo_model/__init__.py

* Analyze & List Query에 lookup, addFields 옵션 추가

add: Analyze & List Query에 lookup, addFields 옵션 추가
