src/spaceone/core/logger/__init__.py, src/spaceone/core/logger/filters/transaction.py, src/spaceone/core/service/service.py
=> feat: add user_id in logger formatter

src/spaceone/core/config/default_conf.py, src/spaceone/core/fastapi/server.py
- Add config for rest server
- Refactor rest server logic
=> Refactor Rest Server Logic

src/spaceone/core/model/mongo_model/__init__.py
- Add allowDiskUse option to stat method of mongo model
- ref: https://www.mongodb.com/docs/manual/reference/method/cursor.allowDiskUse/
=> feat: add allowDiskUse option to mongo model

src/spaceone/core/model/mongo_model/__init__.py
- Fix incorrect allow_disk_use option
=> fix: fix allow_disk_use code

src/spaceone/core/model/mongo_model/__init__.py
- Fix invalid allow_disk_use code in mongo model
=> Fix allow_disk_use option 

src/spaceone/core/config/default_conf.py, src/spaceone/core/fastapi/api.py, src/spaceone/core/fastapi/extension/health.py, src/spaceone/core/fastapi/extension/reflection.py, src/spaceone/core/fastapi/server.py, src/spaceone/core/locator.py, src/spaceone/core/transaction.py
- refactoring server for `fastapi`
- add `REST_EXTENSION_ROUTERS` 
* #11
=> Refactoring rest server for fastapi

.github/PULL_REQUEST_TEMPLATE.md, src/spaceone/core/handler/mutation_handler.py
- Add the following authorization scope (`DOMAIN_OR_USER`, `PROJECT_OR_USER`)
- Add PULL_REQUEST_TEMPLATE.md
=> Add Authorization Scope

src/spaceone/core/handler/mutation_handler.py
Remove authorization scope
- `DOMAIN_OR_USER`
- `PROJECT_OR_USER`
=> Rollback Authorization Scope

pkg/pip_requirements.txt, src/setup.py
Signed-off-by: Minho Kim <mino@megazone.com>
- add new packages for console-api-v2
* #11
=> Add fastapi-utils and pydantic packages

src/spaceone/core/error.py, src/spaceone/core/fastapi/api.py, src/spaceone/core/fastapi/server.py
Signed-off-by: Minho Kim <mino@megazone.com>
- add Request Timeout Error class
- change parse_request method in `fastapi/api.py`
* #11
=> Add Request Timeout Error class

src/spaceone/core/fastapi/api.py
Signed-off-by: Minho Kim <mino@megazone.com>
- add resource and verb parameter for parse_request
- some micro service need `resource` and `verb` parameter
* #11
=> Add resource and verb parameter for parse_request

src/spaceone/core/pygrpc/client.py
- Change channel readiness check logic
- Change TLS termination logic
=> Refactor TLS Termination

src/spaceone/core/pygrpc/message_type.py
- Add gRPC message type to support AnalyzeQuery
=> Add Message Type

src/spaceone/core/pygrpc/message_type.py
- add analyze_query type
- add time_series_analyze_query type
=> Add gRPC Message Type

src/spaceone/core/error.py, src/spaceone/core/locator.py, src/spaceone/core/pygrpc/client.py
=> Refactor Error Class

src/spaceone/core/model/__init__.py, src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/service/__init__.py, src/spaceone/core/service/utils.py
- implement `analyze` method to MongoModel
- add `set_query_page_limit` decorator to service utils
=> Add Analyze Query

src/spaceone/core/utils.py
Signed-off-by: seolmin <seolmin@megazone.com>
* add string_to_hash method in utils
=> add string_to_hash method in utils

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/model/mongo_model/stat_operator.py, src/spaceone/core/pygrpc/message_type.py
- add select option to `AnalyzeQuery`
- refactor message type of `AnalyzeQuery`
- remove debug code
=> Improve AnalyzeQuery

src/spaceone/core/model/mongo_model/__init__.py
- change `granularity` to optional field in analyze query
- fix typo
=> Refactor Analyze Query

src/spaceone/core/handler/authentication_api_key_handler.py
- stop API key support for version 2020-03-04
=> Deprecate Old API Version

src/spaceone/core/config/default_conf.py, src/spaceone/core/fastapi/extension/reflection.py, src/spaceone/core/fastapi/server.py
Signed-off-by: Minho Kim <mino@megazone.com>
- fastapi server command
=> Fastapi server command

src/setup.py
- change required pip packages
=> refactor: change required packages

src/spaceone/core/utils.py
- Add json utils (`save_json_to_file`)
=> feat: add json utils

src/spaceone/core/connector/space_connector.py
- add static endpoint option to SpaceConnector
=> feat: add endpoint option to SpaceConnector

src/spaceone/core/locator.py
- fix connector config bug when calling connector using object
=> fix: fix connector config bug when calling connector using object

src/spaceone/core/handler/authorization_handler.py
=> etc: add debug print

src/spaceone/core/connector/space_connector.py, src/spaceone/core/handler/authorization_handler.py
- fix typo in `space_connector.py`
=> Fix connection bug in SpaceConnector

src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/locator.py
=> Add print log

src/spaceone/core/connector/space_connector.py, src/spaceone/core/locator.py
=> Add logger

src/spaceone/core/locator.py
=> etc: add logger

src/spaceone/core/locator.py
=> Modify connector name

src/spaceone/core/locator.py
=> remove log

.dockerignore, Dockerfile, templates/opt/cloudforet/__init__.py, templates/opt/cloudforet/extension/__ini__.py
- Dockerfile and template has been added
=> feat: add Dockerfile and template

.dockerignore, Dockerfile, src/spaceone/core/locator.py, templates/opt/cloudforet/__init__.py, templates/opt/cloudforet/extension/__ini__.py
- Add Dockerfile and templates of application extension
=> Feature GitHub actions

src/spaceone/core/handler/mutation_handler.py
=> fix: fix permission bug

src/spaceone/core/model/mongo_model/__init__.py
- fix dot(.) bug in analyze query of mongo model
=> refactor: fix dot(.) bug in analyze query

src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/model/mongo_model/stat_operator.py
- add size operator to `select` option
- add sum operator to `select` option
- add key field to `push` operator
=> Add operator to analyze query

src/spaceone/core/handler/authorization_handler.py
* change response method to get values in authorization_handler
=> Change response method to get values in authorization_handler

src/spaceone/core/config/default_conf.py
As the handler uses SpaceConnector, microservices that are not previously used also require default settings.
=> Add default value of connector configuration in default_conf

src/spaceone/core/config/default_conf.py, src/spaceone/core/handler/authentication_api_key_handler.py, src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/handler/authorization_handler.py
* change str type to object type when using locator to get SpaceConnector in handler
=> Change str type to object type when using locator to get SpaceConnector in handler

src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/model/mongo_model/stat_operator.py
- add date_to_string operator to project option in analyze query
=> feat: add date_to_string operator to project option in analyze query

src/spaceone/core/token.py
etc: add method name for import
=> Add method name for import

src/spaceone/core/pygrpc/message_type.py
- add wellknown message types for gRPC
=> Add Wellknown Message Types

src/spaceone/core/config/default_conf.py, src/spaceone/core/opentelemetry/metrics.py, src/spaceone/core/opentelemetry/tracer.py
* add validation code for when endpoint is None when setting Otel
=> Add validation code for when endpoint is None when setting Otel

src/spaceone/core/config/default_conf.py, src/spaceone/core/fastapi/server.py, src/spaceone/core/opentelemetry/tracer.py, src/spaceone/core/pygrpc/server.py, src/spaceone/core/scheduler/scheduler.py, src/spaceone/core/scheduler/worker.py, src/spaceone/core/service/service.py, src/spaceone/core/transaction.py
- change OTEL start process
- change LOGGER start process
- change the OTEL Exporter if the endpoint is not set
=> Fix Otel Bugs

src/spaceone/core/model/mongo_model/__init__.py
=> fix: fix a field_group key bug

src/spaceone/core/base.py, src/spaceone/core/transaction.py
- change transaction load logic
- change transaction deletion logic
=> Refactor Transaction

src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/model/mongo_model/stat_operator.py
- convert datetime type to string type in stat query
=> refactor: convert datetime type to string type in stat query

src/spaceone/core/service/service.py
* Remove response Handlers in pipeline of service
=> Remove response Handlers in pipeline of service

src/spaceone/core/service/service.py
* Add debug code for test of memory leak
=> Add debug code for test of memory leak

src/spaceone/core/service/service.py
=> Remove logger

src/spaceone/core/fastapi/api.py, src/spaceone/core/pygrpc/api.py, src/spaceone/core/service/service.py
* add skip_error_log option to meta of error when error occurs in service
=> Resolve duplication of error logs

src/spaceone/core/config/default_conf.py, src/spaceone/core/model/mongo_model/__init__.py
- add `DATABASE_NAME_PREFIX` to default configuration
- add default `DATABASES` and `CACHES` configurations
=> feat: add DATABASE_NAME_PREFIX configuration

src/spaceone/core/model/mongo_model/__init__.py
- add YEARLY option to analyze query
=> feat: add YEARLY option to analyze query

src/spaceone/core/model/mongo_model/__init__.py
- add `start_field` and `end_field` options to analyze query
=> refactor: add option to analyze query

src/spaceone/core/model/mongo_model/__init__.py
- add `allow_disk_use` option to analyze query
=> feat: add allow_disk_use option to analyze query

pkg/pip_requirements.txt, src/setup.py, src/spaceone/core/command.py
- change require pip packages
- change help message for `spaceone` command
=> Refactor SpaceONE Command

src/spaceone/core/locator.py, src/spaceone/core/pygrpc/api.py, src/spaceone/core/pygrpc/client.py
- remove unused func
- add error directory to skeleton
- fix message conversion issue
- refactor grpc stub
=> Refactor SpaceONE Core 2.0

src/spaceone/core/command.py
=> fix: fix typo

src/spaceone/core/cache/__init__.py, src/spaceone/core/cache/local_cache.py, src/spaceone/core/cache/redis_cache.py
=> fix: fix wrong cache config issue

src/spaceone/core/pygrpc/server.py
- fix bug in gRPC Server when app is not defined
=> Fix gRPC Server Error

src/spaceone/core/config/__init__.py
=> fix: fix config bug

src/spaceone/core/command.py, src/spaceone/core/config/__init__.py, src/spaceone/core/config/default_conf.py, src/spaceone/core/fastapi/server.py, src/spaceone/core/handler/event_handler.py, src/spaceone/core/plugin/__init__.py, src/spaceone/core/plugin/plugin_conf.py, src/spaceone/core/plugin/server.py, src/spaceone/core/pygrpc/__init__.py, src/spaceone/core/pygrpc/api.py, src/spaceone/core/pygrpc/server.py, src/spaceone/core/service/__init__.py, src/spaceone/core/service/service.py, src/spaceone/core/service/utils.py
- Implement plugin server and execution command
=> Implement Plugin Server 

src/spaceone/core/connector/__init__.py, src/spaceone/core/locator.py
=> fix: fix connector config bug

src/spaceone/core/locator.py
- [ㅌ] Bug fix
- fix connector bug in locator
=> fix: fix connector bug in locator

pkg/pip_requirements.txt, src/setup.py, src/spaceone/core/service/utils.py
- change require pip packages
- refactor convert_model decorator
=> Change PIP Packages

src/spaceone/core/command.py, src/spaceone/core/model/mongo_model/__init__.py
- change the following command options
```
spaceone run grpc-server <package>
spaceone run rest-server <package>
spaceone run scheduler <package>
spaceone run plugin-server <package>
```
=> Change Run Commands

src/spaceone/core/command.py
- add module path option for importing external python modules
=> refactor: add module path option

src/spaceone/core/model/mongo_model/__init__.py
=> feat: add unwind option to query

src/spaceone/core/model/mongo_model/__init__.py
- add unwind filter option to query
=> feat: add unwind filter option to query

src/spaceone/core/command.py, src/spaceone/core/plugin/server.py, src/spaceone/core/pygrpc/server.py
- add extension servicer to plugin server
- refactor python path settings
=> Refactor Plugin Server

src/spaceone/core/pygrpc/server.py
- fix function name in pygrpc server
=> fix: fix func name

src/spaceone/core/utils.py
- change logic in `get_dict_value` function
=> refactor: change logic in get_dict_value func

src/spaceone/core/utils.py
=> chore: remove debug code

src/spaceone/core/model/mongo_model/__init__.py
- change response of `to_dict` function in MongoModel
=> refactor: change response of to_dict func in MongoModel

src/spaceone/core/pygrpc/api.py
- fix message bug in `dict_to_message` function
=> fix: fix message bug in dict_to_message func

src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/service/__init__.py
- remove unused imports
- refactor import of service utils
=> Refactor Service

src/spaceone/core/service/__init__.py, src/spaceone/core/service/utils.py, src/spaceone/core/transaction.py
- fix transaction bug
- add type hint
=> fix: fix transaction bug

src/spaceone/core/error.py, src/spaceone/core/handler/__init__.py, src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/service/__init__.py, src/spaceone/core/service/utils.py
- apply permission by resource group
=> feat: apply permission by resource group

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/locator.py
- change backend settings in locator
=> Refactor Locator

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/logger/__init__.py, src/spaceone/core/logger/filters/error.py, src/spaceone/core/logger/filters/exclude.py, src/spaceone/core/logger/filters/masking.py, src/spaceone/core/logger/filters/message.py, src/spaceone/core/logger/filters/parameter.py, src/spaceone/core/logger/filters/traceback.py, src/spaceone/core/logger/filters/transaction.py
=> refactor: change default log message

src/spaceone/core/handler/authorization_handler.py
- change permission logic by resource group
=> refactor: change permission logic by resource group

src/spaceone/core/connector/space_connector.py
- set a space_connector name for configuration
=> fix: set space_connector name for configuration

src/spaceone/core/connector/space_connector.py, src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/handler/mutation_handler.py, src/spaceone/core/service/__init__.py, src/spaceone/core/transaction.py
=> refactor: refactor authorization

src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/handler/mutation_handler.py
=> refactor: change authorization policy

src/spaceone/core/error.py, src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/handler/mutation_handler.py
- change authorization policy in USER Role Type
- implement system token
=> Implement System Token

src/spaceone/core/connector/space_connector.py
=> refactor: change metadata policy in space connector

src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/service/__init__.py
=> Fix Metadata Bug

src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/scheduler/scheduler.py, src/spaceone/core/service/utils.py
- change authorization policy
- apply black formatter
=> Change Authorization Policy

src/spaceone/core/connector/space_connector.py
- modify x metadata so that it can only be changed with arguments
=> refactor: modify x metadata so that it can only be changed with arguments

src/spaceone/core/model/mongo_model/__init__.py
=> refactor: change sort options

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/handler/authorization_handler.py
- optimize permission check logic
=> refactor: optimize permission check logic

src/spaceone/core/error.py, src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/scheduler/worker.py
=> Change Debug Message

src/spaceone/core/handler/authorization_handler.py, src/spaceone/core/model/__init__.py, src/spaceone/core/model/mongo_model/__init__.py
- fix authorization bug
- add option to `model.init_all` func
=> fix: fix authorization bug

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/handler/mutation_handler.py
- change authorization policy of system token
=> refactor: change authorization policy of system token

src/spaceone/core/handler/authentication_handler.py
=> refactor: refactor check logic of app

src/spaceone/core/model/mongo_model/__init__.py
- apply trim to strings when creating or updating database
=> refactor: apply trim to strings when creating or updating database

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/scheduler/worker.py
- change debug log message
- change the token to only allow version `2.0`
=> Change Token Policy

src/spaceone/core/handler/authentication_handler.py, src/spaceone/core/pygrpc/api.py, src/spaceone/core/utils.py
- apply internal authentication
=> feat: apply internal authentication

src/spaceone/core/model/mongo_model/__init__.py
=> refactor: change index policy

src/spaceone/core/model/mongo_model/__init__.py
- fix memory issue in stat query
=> fix: fix memory issue in stat query

src/spaceone/core/scheduler/worker.py
=> fix: fix wrong error handling

src/spaceone/core/model/mongo_model/__init__.py
- add unwind option to analyze query
=> feat: add unwind option to analyze query

src/spaceone/core/model/mongo_model/__init__.py, src/spaceone/core/pygrpc/client.py
- add return_type to stat query
- add return_type to analyze query
- fix lint
=> Add Query Option

src/spaceone/core/model/mongo_model/__init__.py
- add debugging code to distinct query
=> chore: add debugging code

src/spaceone/core/service/__init__.py
- modify log format, add response time
=> Modify log format, add response time

src/spaceone/core/handler/authentication_handler.py
- add user_groups info at metadata
=> Add user_groups info at metadata

src/spaceone/core/handler/authorization_handler.py
- modify user_projects check logic with wildcard
=> Modify user_projects check logic with wildcard

src/spaceone/core/model/mongo_model/__init__.py
* Add include_count option to query
=> Add include_count option to query
